### PR TITLE
Message added on visualize error on forceful termination

### LINKED ISSUE #333: bug: Analysing dataError: ENOENT: no such file or directory [...]<pid>.clinic-doctor-processstat
Hi 👋 

Here I bug I faced today. I'm obviously available to help 🤚. Didn't have time to debug yet. If you have any insights feel free to share it ^^

## Expected Behavior
A `*.clinic-doctor-processstat` file should be generated.

## Current Behavior
The doctor command doesn't work due to this file missing.

## Steps to Reproduce (for bugs)

1. Use this `fail.js`script:
```js
#!/usr/bin/env node

const async = require('async');
const shell = require('shelljs');

module.exports = function (exit) {
  async.waterfall([
  function (next) {
    next();
  },
  function (next) {
    next();
  }
  ], exit);
};

!module.parent && module.exports(shell.exit);
```

1. Run `clinic doctor -- node fail.js`
2. Got this error:
```bash
Analysing dataError: ENOENT: no such file or directory, open '.clinic/7063.clinic-doctor/7063.clinic-doctor-processstat'
```

## Sample upload
Screenshot 2022-02-07 at 17 06 58

## Environment
* Clinic.js version: `v11.0.0`
* Doctor version= `v9.2.1`
* Node.js version: `v17.4.0`
* Npm: `v8.3.1`
* Browser name and version: Firefox 96.0.3
* Operating system and version: OSX 12.1.0

### PR DESCRIPTION
**Pull request by Ceres6**
Closes #333

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
This fails on windows due to no `shell`.  Can you adjust the test to use `process.exit` instead?

**Comment by Ceres6** [comment]
Sure! Done!

**Comment by RafaelGSS** [comment]
@Ceres6 this keeps failing

**Comment by Ceres6** [comment]
Sorry, file name mismatch 🤦🏻

**Comment by Ceres6** [comment]
It seems node 14 handles differently creating a read stream from an unexisting file than 16/18 and therefore no error is brought up and the new test fails. 
For the failing node 18 tests in Windows and Ubuntu they are not the new one and don't seem to be related with the changes I made so I'm not sure about what we should do here @RafaelGSS

**Comment by RafaelGSS** [comment]
You can skip v14 in the tests

**Comment by Ceres6** [comment]
Should I skip v14 only for that test or in general?

**Comment by Ceres6** [comment]
I'm not being able to skip the test, I was trying with the `--grep` option of tap but it keeps running all the test no matter what I pass. Any ideas?

**Comment by simoneb** [comment]
@Ceres6 https://node-tap.org/docs/api/#ttestname-options-function. see skip option

**Comment by simoneb** [comment]
@Ceres6 I realize you're now busy on something else but it would be good to get this out the door.

**Comment by Ceres6** [comment]
I will try to find some time in this week to see if I can fix it.

**Comment by Ceres6** [comment]
Just to be aware. I'm testing with node 18.10 (instead of 18.13) and there are a lot less failing tests. Maybe something has changed in the latest version and now it is receiving SIGABRT instead of logging the output

**Comment by RafaelGSS** [comment]
@Ceres6 can you rebase on main? See also #393

**Comment by Ceres6** [comment]
Rebased, I have seen the issue, it's what I thought. Let me know if I can help with that in any way.

**Review by RafaelGSS — APPROVED** [review]

**Pull request merged**
