### PR TITLE
chore: drop v12 support

### PR DESCRIPTION
**Pull request by RafaelGSS**

### CODE REVIEW

**Review by simoneb — APPROVED** [review]
Didn't we do this already not too long ago?

**Comment by RafaelGSS** [comment]
Actually, we've added support to the v16+

**Comment by RafaelGSS** [comment]
Btw, let's wait for: 

[https://github.com/clinicjs/node-clinic-doctor/pull/376](https://github.com/clinicjs/node-clinic-doctor/pull/376)

[https://github.com/clinicjs/node-clinic-heap-profiler/pull/73](https://github.com/clinicjs/node-clinic-heap-profiler/pull/73)

[https://github.com/clinicjs/node-clinic-bubbleprof/pull/400](https://github.com/clinicjs/node-clinic-bubbleprof/pull/400)

So we can bump all those in a single major release

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
