### PR TITLE
Add heap profiler to the CLI

### PR DESCRIPTION
**Pull request by ShogunPanda**
## What's in there?

This PR add support for the Heap Profiler and memory flame charts via https://github.com/clinicjs/node-clinic-heap-profiler.

## Notes to reviewers

This PR cannot be merged until https://github.com/clinicjs/node-clinic-heap-profiler/pull/1 lands and the package is finally released on NPM.

### CODE REVIEW

**Review by jasnell — APPROVED** [review]
Provisional LGTM. 

Looks like there are a couple of extra commits here and we obviously need to make the heap-profiler repo public and get the tool merged in before this can land.

**Comment by jasnell** [comment]
@mcollina ... where are we at on this particular piece? Is this ready for prime time?

**Comment by mcollina** [comment]
more or less!

**Comment by jasnell** [comment]
This will need to be rebased to drop the first two commits, and again after https://github.com/clinicjs/node-clinic-heap-profiler/pull/8 lands. The CI won't pass until after we get the `@nearform/heap-profiler` package published to npm

**Comment by jasnell** [comment]
The test suite is failing on Node.js 10.x ... I'm going to ignore those failures when landing this because the next step will be to drop 10.x from our support matrix.

**Pull request merged**
